### ISSUE TITLE
_type parameter does not validate resource types 

### ISSUE THREAD

**Issue by LTA-Thinking** [microsoft/fhir-server#1151]
**Describe the bug**
When searching with the _type parameter the resource types are not validated. If a resource type is not recognized, then it is ignored. This causes a typo to return the same results as there being no matches. 

**To Reproduce**
1. Conduct a global search with _type=notreal

**Expected behavior**
An operation outcome is returned stating that the resource type is invalid.

**Actual behavior**
An empty bundle is returned.

---

**Edit:** See [below](#issuecomment-726367437), if possible, we should not throw exceptions where previously the response was allowed. This looks to be one of those cases where the error can be reported with the output

**Comment by CaitlinV39** [comment]
@LTA-Thinking was this resolved with #1139 or is there more work to do?

**Comment by LTA-Thinking** [comment]
@CaitlinV39 The issue was discovered while working on #1139. It has not been fixed yet.

**Comment by CaitlinV39** [comment]
AB#76266

**Comment by Ivanidzo4ka** [comment]
There is certain uncertainty how to handle `_type` parameter for non global case.
Like `http://server/Observation?_type=Patient` doesn't make much sense to me.
In same time `http://server/Observation/[id]/*?_type=Patient` does.

**Comment by brendankowitz** [comment]
@CaitlinV39 I'm reviewing this requirement again, this could be potentially breaking for a customer, it will throw a BadRequest where the invalid type was previously ignored. Suggestion is we add the invalid type message to the bundle like here: https://github.com/microsoft/fhir-server/blob/master/src/Microsoft.Health.Fhir.Shared.Core/Features/Search/SearchOptionsFactory.cs#L150

**Comment by CaitlinV39** [comment]
@brendankowitz that makes sense to me and I can document that we updated the bundle. I don't want to throw the BadRequest.

**Comment by Ivanidzo4ka** [comment]
@brendankowitz @CaitlinV39 
So for the case of `?_type=Patient,foo` I think we can all agree it should do search for `Patient` only and add message what `foo` is unknow.
But what should be the case for `?type=foo`? We can ignore type and in this [case](https://www.hl7.org/fhir/search.html#_type):
`If no type is specified, the only search parameters that be can be used in global search like this are the base parameters that apply to all resources.`
Or we can don't do search at all, since we know it's pointless.

Second implementation would align with what we do right now.

Which brings my second question. In my PR @brendankowitz  mention what it would be nice to clean up  self url and next url links from invalid parameters.

So if I have `http://server/Observation?_type=Patient,foo`
self link and next link should look like 
`http://server/Observation?_type=Patient`
and 
`http://server/Observation?_type=Patient&ct=#ContinuationToken`

Imagine I call ` `http://server/Observation?_type=foo`
If I stick to current behavior this search should yield nothing and I assume I need to leave self link and next link as is.

Which I find a bit confusing, that rule of we remove invalid parameters but only if we have at least one valid one, otherwise we leave things as is, sound a bit complex and confusing for me.

Can we stick to just notifying user about invalid types and leave urls as is?

**Comment by CaitlinV39** [comment]
@Ivanidzo4ka my thoughts are leave the behavior as it is today where ?type=foo I would just not do the search. I'm okay with just notifying the user and leaving URLs but would like @brendankowitz  to weigh in on this too.

**Comment by Ivanidzo4ka** [comment]
One other hand there is this issue:
https://github.com/microsoft/fhir-server/issues/620
Which clearly wants to strip unsupported parameters from url. @johnstairs any chance you remember reasoning for that decision?

**Comment by brendankowitz** [comment]
Going to try and summarize our discussion on this:

- The values of a parameter, such as `_type` are on the right-side of the equation, so we will treat them as input data to match against
- `_type` is an enumeration, since we know all possible values, having an invalid value in this array should result in BundleIssue being added (an OperationOutcome included in the resulting bundle)
- We will not remove it from the URL (self/next link), no results will be returned because there will be no matches
- Results may be returned in the case of multiple types where one was a match, e.g. `_type=foo,Observation`
- In the future, as detailed in #1050, the client could opt for an error to be returned in cases such as this

Let me know if I missed anything, @Ivanidzo4ka, @johnstairs, @CaitlinV39
