### ISSUE TITLE
Clone issue

### ISSUE THREAD

**Issue by armanpetrosyan23** [microsoft/fhir-server#1171]
Hello, I want to clone this project but always recive same VS error` 
![image](https://user-images.githubusercontent.com/35919382/88536456-e6ea5500-d01c-11ea-9e8d-92c0f596eb9e.png)

**Comment by brendankowitz** [comment]
Hi @armanpetrosyan23, have you tried walking through our setup guide here: https://github.com/microsoft/fhir-server/wiki/Build-and-debug-locally?

**Comment by Ivanidzo4ka** [comment]
This is probably because you have different version of dotnet core3.1
Type in your command line dotnet --version and check what version of .net core3.1 do you have.
Go to you local https://github.com/microsoft/fhir-server/blob/master/global.json  file and change it to your local version.

After changes are made in global.json file, reload Visual studio.

**Comment by hansenms** [comment]
I would recommend downloading the version in the `global.json` and installing it rather than switching to another version. We fix the version to avoid some side effects with different versions.

**Comment by CaitlinV39** [comment]
@armanpetrosyan23 I'm going to close this issue based on the suggestions in the comments but if you are still having any issues let us know and we can revisit. Thanks!
