### ISSUE TITLE
OpenAPI documentation

### ISSUE THREAD

**Issue by SychevIgor** [microsoft/fhir-server#1264]
**User story**
As a application developer, I want see object schema for each api call so that I can easily develop my consumer application.

**Acceptance criteria**
1. When application started in dev environment, then I can see openAPI UI page and documentation in swagger format.

With this openapi- we will be able to publish swagger via Azure API Management easier. 
https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?view=aspnetcore-3.1

**Comment by CaitlinV39** [comment]
@SychevIgor The FHIR community has information on its capability statement [here](http://build.fhir.org/capabilitystatement.html). On that page, there is a link to the [OpenAPI specification](https://github.com/OAI/OpenAPI-Specification). The functionality can change based on how it is implemented. Let me know if this helps!

**Comment by SychevIgor** [comment]
It would be nice to have this openapi auto-generated documentation as part of FHIR server. I'm sure that Microsoft implemented it exactly as in a specification, but host auto-generated documentation with app all together - will give some benefits for those of us who are extending microsoft fhir and not using paas version

**Comment by CaitlinV39** [comment]
@SychevIgor the FHIR Servers do a lot of work to product the capability statement. Because of this, we would need to first convert the capability statement into a swagger and then display that swagger in the UI.  For testing, tools like postman can be really helpful and the https://fire.ly/fhir-api/ has a lot of information as well. For now, we're going to close this as won't fix but can reopen in the future if we see a high demand.

**Comment by vijay2358** [comment]
Is there any reference or sample refer swagger-Ui- we need the swagger-UI for payers as per CMS guidelines. Do we anything we generated the swagger from azure API or from capabilities statement
