### ISSUE TITLE
Search strings should be accent-insensitive

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#1364]
**Describe the bug**
Currently the search indexing is case-insensitive, but is not accent-insensitive. 

**FHIR Version?**
All

**Data provider?**
CosmosDB

**To Reproduce**
1. Add a name to Patient with an accent, e.g. "Müller"

**Expected behavior**
When searching, as mentioned in the [spec](https://www.hl7.org/fhir/search.html#ptypes), the search should work for "muller"

**Actual behavior**
Search is accent sensitive

**Comment by johnstairs** [comment]
This works properly in SQL.

**Comment by brendankowitz** [comment]
Thanks John, updated!

**Comment by CaitlinV39** [comment]
AB#76718

**Comment by Ivanidzo4ka** [comment]
It works properly because SQL server support it on collation level (either whole database, or specific column can be assign with specific collation which defines how things encoded, and how to perform string comparisons).

There is no such thing in CosmosDB as far as I can see. They "recently" [added ](https://devblogs.microsoft.com/cosmosdb/new-string-function-performance-improvements-and-case-insensitive-search/) case insensitivity option for strings but we don't use them right now.

IMHO in order to work this right on both platforms there is two options:
a) Wait till CosmosDB will come up with accent insensitive string operations 
Pros: would probably work without much changes 
Cons: Unknown amount of waiting time, unless we have contacts with cosmos team

b) Push normalization of strings on higher level, and do it during document parsing/search param extraction. 
Pros: Would work independent from persistent level.
Cons: Need to add additional normalization logic in code. Data already in storage need to be updated (vehicle is a bit unclear, probably can be part of reindex job)

Thoughts? @CaitlinV39 @brendankowitz 

Also do you want me to fill bug for case-insensitive not working for cosmos? I can at least fix it right now.

**Comment by brendankowitz** [comment]
It would be nice if the DB support this, but if we don't have that option, how reliably can we do this at an app level?
I'm also not sure of the caveats of using a .net package like System.Text.Encoding.CodePages vs 3rd party like https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Analysis.Common/Analysis/Miscellaneous/ASCIIFoldingFilter.cs.

Lets log a separate bug for case-insensitive searches if this isn't working, this test has cities in both cases: https://github.com/microsoft/fhir-server/blob/master/test/Microsoft.Health.Fhir.Shared.Tests.E2E/Rest/Search/BasicSearchTests.cs#L70

**Comment by Ivanidzo4ka** [comment]
Yeah, I can see it's working, but I don't understand why it's working....
This is a snippet from query:
`AND EXISTS (SELECT VALUE si FROM si IN r.searchIndices WHERE si.p = @param2 AND STARTSWITH(si.n_s, @param3))`

https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-startswith
bool_expr Optional value for ignoring case. When set to true, STARTSWITH will do a case-insensitive search. When unspecified, this value is false.

It's clearly unspecified, but it works. At least in my cosmos emulator.
It either documentation is lying or maybe emulator is not following specification. Not an expert in cosmos.

Regarding moving it to app level, there is [string.Normalize](https://docs.microsoft.com/en-us/dotnet/api/system.string.normalize?view=netcore-3.1#System_String_Normalize_System_Text_NormalizationForm_).
If you fall down the rabbit hole of links you end up on this page: 
https://unicode.org/reports/tr15/ probably a good readout for Friday evening, but you can see complexity of problem. Dotnet has solution, but I never work with it, so I would say it need some investigation.

**Comment by brendankowitz** [comment]
> Yeah, I can see it's working, but I don't understand why it's working....
> This is a snippet from query:
> `AND EXISTS (SELECT VALUE si FROM si IN r.searchIndices WHERE si.p = @param2 AND STARTSWITH(si.n_s, @param3))`

We store a normalized value in a different field the (`n_` field): https://github.com/microsoft/fhir-server/blob/master/src/Microsoft.Health.Fhir.CosmosDb/Features/Storage/Search/SearchIndexEntryJObjectGenerator.cs#L116

**Comment by Ivanidzo4ka** [comment]
Cool, I'm learning more and more.
I guess there is opportunity to don't use that field at all if we decide to go with storage based solution. Or repurpose it for accent normalization.

**Comment by CaitlinV39** [comment]
I'm closing this for now as we won't fix in Cosmos DB. THis already works on SQL.
