### ISSUE TITLE
Search Patient by Managing Organization does not work

### ISSUE THREAD

**Issue by andreracz** [microsoft/fhir-server#1418]
**Describe the bug**
I'm trying to search a patient by Managing Organization and it does not work. 

**FHIR Version?**
R4

**Data provider?**
CosmosDB (using the managed version)

**To Reproduce**
1. Create a new Organization with value:
{
        "resourceType": "Organization",
        "name": "ORG 1"
} 
2. Get the ID from the org (in my case:  e9c9376a-9206-4656-ba33-faeec3bf0ba5)
3. Create a new Patient, with contents:
{
        "resourceType": "Patient",
        "name": [
          {
            "use": "official",
            "text": "PACIENTE TESTE 2"
          }
        ],
        "gender": "female",
        "birthDate": "2019-02-16",
        "managingOrganization": {
            "type": "Organization",
            "id": "Organization/e9c9376a-9206-4656-ba33-faeec3bf0ba5"
        }
      }

4. Search with any of the following URLs: /Patient?organization=e9c9376a-9206-4656-ba33-faeec3bf0ba5
/Patient?organization=Organization/e9c9376a-9206-4656-ba33-faeec3bf0ba5

**Expected behavior**
Patient to be returned

**Actual behavior**
Empty bundle returned:

{
    "resourceType": "Bundle",
    "id": "27d6f4db78030e4eac7fc428d3f4328a",
    "meta": {
        "lastUpdated": "2020-11-03T17:26:52.2721003+00:00"
    },
    "type": "searchset",
    "link": [
        {
            "relation": "self",
            "url": "https://xxxxxxxxx.azurehealthcareapis.com/Patient?organization=e9c9376a-9206-4656-ba33-faeec3bf0ba5"
        }
    ]
}

**Comment by andreracz** [comment]
Also, trying to include the managing organization when getting the pacient does not works. Should be related.
Using URL: 
https://xxxxxx.azurehealthcareapis.com/Patient?_include=Patient:managingOrganization

The return is: 
 {
    "resourceType": "OperationOutcome",
    "id": "7a7ab8681f49374099cba6aedfbddf43",
    "issue": [
        {
            "severity": "error",
            "code": "forbidden",
            "diagnostics": "The search parameter 'managingOrganization' is not supported for resource type 'Patient'."
        }
    ]
}

Using https://xxxxx.azurehealthcareapis.com/Patient?_include=Patient:organization or https://xxxxx.azurehealthcareapis.com/Patient?_include=Patient:*

the return is: 

{
    "resourceType": "OperationOutcome",
    "id": "a622737868b30c499bd770984df6c5c0",
    "issue": [
        {
            "severity": "error",
            "code": "forbidden",
            "diagnostics": "Include expression is not supported."
        }
    ]
}

**Comment by Ivanidzo4ka** [comment]
Thank you reaching to us.
Few comments:

-  `/Patient?organization=e9c9376a-9206-4656-ba33-faeec3bf0ba5`
I believe case insensitivity for search parameters is not specified in standard, so that link should be `Patient?Organization=e9c9376a-9206-4656-ba33-faeec3bf0ba5` because resource type you filtering on is `Organization`. And it works for me to some extent. (More below)

- `/Patient?organization=Organization/e9c9376a-9206-4656-ba33-faeec3bf0ba5` I don't think it's a valid search as well, it should be `/Patient?Organization=Organization/e9c9376a-9206-4656-ba33-faeec3bf0ba5` if you want to filter by Type and 
`Patient?managingOrganization="Organization/62bc3659-64c9-4425-b7fe-dca4f404a4b9` if you want to filter by field in patient.

What is weird for if I create two same patients with only difference in organization I would get both patients back no matter first or second organization I'm using for filtering.
I need to look into that.

For `_include` I know `_include` is currently not supported in cosmos, but I don't know much details about that.

**Comment by Ivanidzo4ka** [comment]
AFAIK `_include` is not supported with Cosmos backend.
So let's move to normal searches.
```
{
"resourceType": "Patient",
"name": [
{
"use": "official",
"text": "PACIENTE TESTE 2"
}
],
"gender": "female",
"birthDate": "2019-02-16",
"managingOrganization": {
"type": "Organization",
"id": "Organization/e9c9376a-9206-4656-ba33-faeec3bf0ba5"
}
}
```
this looks like valid patient, but it's not exactly right. 
https://www.hl7.org/fhir/R4/patient-definitions.html#Patient.managingOrganization
should be a reference. 
So part of json should look like this:
```
{
"managingOrganization": {
    "reference": "https://xxxxx.azurehealthcareapis.com/Organization/e9c9376a-9206-4656-ba33-faeec3bf0ba5"
}
}
```
And if I insert that patient, I can find it. 

There is still question what should we do in case if we got provided partially wrong data.

**Comment by andreracz** [comment]
Ok, my mistake, I was inserting a wrong reference. Want me to close this or leave it open for dealing with the input error?

**Comment by Ivanidzo4ka** [comment]
I would leave it open for now, I find it strange what for STU3 we actually throw error if you pass us non valid code, but for R4 it's ok to accept such input.

**Comment by Ivanidzo4ka** [comment]
http://hl7.org/fhir/STU3/references.html#Reference vs http://hl7.org/fhir/references.html#Reference
R4 added  
`"type" : "<uri>", // Type the reference refers to (e.g. "Patient")`
Which is why this document is parsed without any error, but in same time it doesn't make much sense for observation to have reference as type, but from standard point of view it's valid input.

**Comment by andreracz** [comment]
Type is OK as per R4, but I had mistaken the reference for ID.

```
"managingOrganization": {
"type": "Organization",
"id": "Organization/e9c9376a-9206-4656-ba33-faeec3bf0ba5" // THIS IS WRONG
}
```

**Comment by brendankowitz** [comment]
Correct, `id` is not valid in a reference object, this should work with R4:
```
"managingOrganization": {
    "type": "Organization",
    "reference": "Organization/e9c9376a-9206-4656-ba33-faeec3bf0ba5" 
}
```

**Comment by CaitlinV39** [comment]
@andreracz we just recently release _include support on CosmosDB, so believe we can close this but let me know if you have any outstanding items

**Comment by andreracz** [comment]
@CaitlinV39, actually, the issue was on my end, but we kept it open because of FHIR not validating the input. This issue can be closed in my point of view.
