### ISSUE TITLE
Connecting my EHR to azure FHIR API

### ISSUE THREAD

**Issue by leo9223** [microsoft/fhir-server#1515]
If we have an EHR deployed on my premises, can we make azure API on top of that exposing my EHR's data via azure FHIR api that is hosted on azure?

Is this possible? or is this a legitimate usecase?

**Comment by brendankowitz** [comment]
Hi @leo9223, I don't think there is a simple answer. You should checkout https://github.com/microsoft/health-architectures or other resources for architecting in a cloud-based FHIR Server. The FHIR Server for Azure stores data locally by default, so it might be possible to synchronize or use it as an HIE. 

If you're looking for a facade that implements the FHIR API over an existing datastore, this would technically be possible, but it would be a non-trivial amount of work, and not something our team directly can provide support for.

**Comment by leo9223** [comment]
Alright thank you.

**Comment by granadacoder** [comment]
This is a very misunderstood concept.


Microsoft Azure FHIR is neither a “Plain Server” (hapi fhir language) nor a “Façade” (vonk language)

The below links describe some other options.

https://hapifhir.io/hapi-fhir/docs/server_plain/introduction.html
 
https://fire.ly/products/fhir-facade/
 

Also:
And (@brendankowitz / others), (and if I recall a conversation / demo at HL7 Dev Days (in person) at the Microsoft campus ) Microsoft Azure FHIR pulls out "all the bells and whistles" to write HIGHLY PERFORMANT CODE against Microsoft Sql Server (you see a lot of CTE's in profiler) and/or CosmosDB.  
While it is coded against interfaces for the data layer, it would be a HUGE undertaking to change to a different RDBMS and get anywhere close to the performance that (this) team has achieved with Microsoft Sql Server/CosmosDB.
Aka, it is not coded against an "ORM" or in some super generic way, because you would never get the performance via an ORM that (this) team has implemented.
