### ISSUE TITLE
Unable to load DB schema

### ISSUE THREAD

**Issue by stephenstack** [microsoft/fhir-server#1789]
Hi

I'm unable to load the DB schema. Set the Automatic Updates to 'True'.
![image](https://user-images.githubusercontent.com/7944609/112718288-ea0a4d80-8ee9-11eb-969b-d5fb85099b77.png)

The migration tool (the docs need a pre-req for dotnet sdk), does not work per the following. Am I not doing something correctly? I'm happy to run the migration sql files directly, but that's not intuitive either. Please help!

C:\Users\Dell>dotnet tool install -g Microsoft.Health.SchemaManager --version 1.0.0-microsoft-data-sqlclient-20200929-1
error NU1101: Unable to find package microsoft.health.schemamanager. No packages exist with this id in source(s): nuget.org
The tool package could not be restored.
Tool 'microsoft.health.schemamanager' failed to install. This failure may have been caused by:

C:\Users\Dell>dotnet tool install -g Microsoft.Health.SchemaManager
error NU1101: Unable to find package microsoft.health.schemamanager. No packages exist with this id in source(s): nuget.org
The tool package could not be restored.
Tool 'microsoft.health.schemamanager' failed to install. This failure may have been caused by:

**Comment by CaitlinV39** [comment]
Thanks so much @stephenstack for the question.

@rbans96 - Can you review this?

**Comment by rbans96** [comment]
Hi @stephenstack - 
If I understand correctly, you want to initialize schema on startup. And that's where you have selected 'auto' value for the field Sql schema automatic updates enabled. It is the right setting to enable auto upgrade of schema over startup. If you click on the little info icon, we can see the details for the option to select.
![image](https://user-images.githubusercontent.com/57157506/112890023-3771f080-908b-11eb-9f17-b568bc88c5b3.png)

So I am wondering, whether you proceeded with the Sql schema automatic updates enabled as 'auto' and did it work for you?

**Comment by Ivanidzo4ka** [comment]
I think this issue is actually two issues. 
First is `auto` in template doesn't work as expected (still need more information what exactly is not working)

Second is package couldn't be found. I think it's problem in our documentation. We need to clearly specify what that command line need to be run from cloned repository (otherwise nuget.config which contains requisites wouldn't be picked by dotnet tool).

**Comment by rbans96** [comment]
Thanks @Ivanidzo4ka! I will definitely take a look how can we make documentation better and intuitive.

@stephenstack For the second point though, the tool can be installed from the public feed. Since latest version(which is optional) will keep on updated based on our release, so its ok if we don't specify a version, since without explicitly specifying version, the package would be installed with the latest version available.

If you follow all the steps as mentioned in the screenshot and hit install command without specifying a version, i.e.
dotnet tool install -g Microsoft.Health.SchemaManager
it should install version 1.2.23 for you(which is latest as of now).
![image](https://user-images.githubusercontent.com/57157506/112915625-85025380-90b3-11eb-9d80-73c15b3466ec.png)

**Comment by Ivanidzo4ka** [comment]
Just few cents.
I think it's overkill to ask people to install visual studio, it's quite big, you need to look for express edition, some probably never work with it.

I can be wrong, but copying [nuget.config](https://github.com/microsoft/fhir-server/blob/main/nuget.config)  to your current folder should be enough (need to be tested)

**Comment by sstackey** [comment]
Thanks for the response all. So yes, its both things... First setting the setting to 'auto' on deploy does not deploy the Database. My Tables are empty... see below.

And yes, the docs are not clear, initally it appeared that I could run the dotnet command from windows cmd prompt. But if VS is needed, that is a 'bazooka'. BUT, @Ivanidzo4ka tip in downloading nuget.config to the current dir worked a treat to get the schema manager installed. Will work on doing the migration and feedback.



![image](https://user-images.githubusercontent.com/78075801/112952118-0ef20100-9134-11eb-8456-12ac3aedd646.png)

**Comment by Ivanidzo4ka** [comment]
@rbans96 posted PR to update documentation and to make sure next time you deploy, schema would be populated.

I think I need to provide some explanation why schema is empty right now.
Schema manager is part of our web app service, it's marked as `IHostedService` and suppose to be running at start of the service.
But there is implementation details problem.

App services (which host aspnetcore site) by default don't run service until someone will send request to service (It's also unload service if no one uses it for long period of time). If no one uses it, what's the point of burning electricity? Which make sense.
Unfortunately that prevent us from running schema update on sql server.

There is PR which would turn off that feature and service would always be on.
For your current service, you can just perform call to your service, and it should populate schema (Simple GET "https://yourhost"/metadata" should be enough)

**Comment by stephenstack** [comment]
Something has changed, for the better.  I just did a fresh deployment today and now all tables are present, GETs and POSTs work just fine with the API. And this without calling the URL per your previous suggestion. Though I guess that makes sense. Now to decipher the schema (because I like to go under the hood). Any docs or points on that would be useful.

**Comment by Ivanidzo4ka** [comment]
We don't have one per se, but schema has somewhat good naming, so most tables are self explanatory.
I can recommend [this video  ](https://www.youtube.com/watch?v=x2eggFN2Puc).

Shorten version of it would be:
There is 3 types of tables.

- `Resource` table where we keep all resources.

- `*SearchParam` tables where we keep extracted from resource values so we can do search on them.

- Dictionary tables. Some string values are predefined, like resource type, or quantity code, so instead of storing them as strings, we store their integer representation.

**Comment by stephenstack** [comment]
@Ivanidzo4ka  thanks for the help and information

**Comment by CaitlinV39** [comment]
@stephenstack I'm going to close this issue but please let us know if you have any additional questions that we can help with!
