### ISSUE TITLE
Provenance - target and version

### ISSUE THREAD

**Issue by ellgre** [microsoft/fhir-server#1854]
We are using headers on PUT and POST to generate Provenance. The provenance is generated as expected, but we have a question regarding target which is not version specific in the provenance objects generated by the FHIR server. Is there any possiblity to make target version specific? Will _revinclude from the changed object work if it is version specific? If not, do you have a recommendation on which field we can use in order to keep track of the version the provenance is related to?

In [FHIR](https://www.hl7.org/fhir/provenance.html) target is described as follows:
target | Σ | 1..* | Reference(Any) | Target Reference(s) (usually version specific)

**Comment by anyname2** [comment]
That would be a nice to have. As a workaround we create Provenance resources manually with versioned references. But AFAIK FHIR currently doesn't support versioned reference search or include either. It always uses latest version and the version is never even extrancted into the index.

I did submit a PR to address `_include` with veriosned references: #1450, which wasn't merged (but we use it in our version to make our workaround useful). It's a start, and there are more things needed to support this scenario.

**Comment by Ivanidzo4ka** [comment]
Would it be ok if target look like: 
`Resource/{ResourceId}/_history/{ResourceVersion}` instead of `Resourse/{ResourceId}`
something like:
`Patient/702532ed-f6e1-4bfd-8ed2-f5bdaa5b7f5f/_history/2`
At least this is what I'm getting from reading docs on Reference type.

I'm not sure about _revInclude, but you can definitely query resource by that url.

If so it's a one minute change in code, and I can submit it after I'm done with tests for my current PR.
https://github.com/microsoft/fhir-server/blob/a2eb81ddf251555d5cc72ddf568945163875daf9/src/Microsoft.Health.Fhir.Shared.Api/Features/Resources/ProvenanceHeaderBehavior.cs#L76

**Comment by ellgre** [comment]
I have tested with target similar to Patient/702532ed-f6e1-4bfd-8ed2-f5bdaa5b7f5f/_history/2 and _revinclude works perfectly. Could your please implement the change?

**Comment by CaitlinV39** [comment]
@Ivanidzo4ka can this be closed?
