### ISSUE TITLE
Remove unused types in a new SQL schema version

### ISSUE THREAD

**Issue by CaitlinV39** [microsoft/fhir-server#1870]
**User story**
Old TVPs were removed from the snapshot file 8.sql in Reindexes resources in bulk in SQL by rotodd · Pull Request #1709 and exceptions were added to the test GivenTwoSchemaInitializationMethods_WhenCreatingTwoDatabases_BothSchemasShouldBeEquivalent.

These types need to be dropped in the diff file of a following version (relevant PR comment here) and the exceptions should be removed from the test.

**Acceptance criteria**
Old types are dropped and the test is updated.

**Comment by davidegiacometti** [comment]
Hi,

this is the comparison between a SQL schema updated from v4 using differential scripts and a fresh v10.
After the update there are 27 more objects (tables, stored procedures and types).

![schema](https://user-images.githubusercontent.com/25966642/119787705-c6578980-bed1-11eb-884d-011c895b9c4c.png)

I suppose these are unused objects and should be removed. Can I have a confirmation?

Thanks

**Comment by brendankowitz** [comment]
It should be safe to drop after all servers are running the latest code. The compatibility we have is that newer code can function with older schemas (we target latest-1), this gives compatibility with rolling upgrades.

**Comment by v-kulkarnipa** [comment]
This is an old issue, is this issue is still relevant. It is noted in the description that the 8.sql file was modified, and the latest schema version is around 82.sql. If changes are needed as described, can you please provide the exact diff file version that requires updates?

From the description, I couldn't determine the exact diff file from which the old TVPs need to be removed.
The snapshot file 8.sql is no longer available in the main branch.

**Comment by evachen96** [comment]
@EXPEkesheth I think this one can be closed, this was in regards to version 8 sql file, and we are currently on 82.sql
