### ISSUE TITLE
INCOMPLETE DATA RETURNED DURING SEARCH

### ISSUE THREAD

**Issue by ellgre** [microsoft/fhir-server#1898]
**Describe the bug**
When we are doing a search to fetch all organizations and use the next link to go through all pages we do not get all organizations.

**FHIR Version?**
R4

**Data provider?**
CosmosDB

**To Reproduce**
1. Make a search to get all organizations
2. Note total
3. Use next link and note number of organizations returned
4. Repeat step 3 until there are no more next links
5. Sum opp the actual organizations returned.
6. The actual number returned is not equal to total.

**Expected behavior**
We expect to get the same number of organizations as total

**Actual behavior**
The total parameter = 2175. With _count = 100 we get 2115 when we go through all pages and with _count=1000 we get 2058 organizations.

Until recently we used a version of FHIR server from autumn 2020, and it worked in that version.

**Comment by CaitlinV39** [comment]
@ellgre - Can you send me the exact search syntax you are using for each one? I'm not able to reproduce so just wanted to see if I am missing something.

**Comment by ellgre** [comment]
We are using the following: <baseurl>/Organization/?_format=application%2Fjson&_count=1000.

**Comment by ebjornset** [comment]
Just want to mention that we are running the 1.3.8 release, with the appsetting FhirServer:CoreFeatures:IncludeTotalInBundle = Accurate

**Comment by Ivanidzo4ka** [comment]
I'm trying to reproduce it (in 1.3.8 release branch), and I have trouble with reproducing it as well.

I've check code, and I don't see (so far) anything what could affect search from generating cosmos query.

Query we send right now is:
```
SELECT c.id,c.isSystem,c.partitionKey,c.lastModified,c.rawResource,c.request,c.isDeleted,c.resourceId,c.resourceTypeName,c.isHistory,c.version,c._self,c._etag, c.searchParameterHash
FROM c
WHERE c.isSystem = false
AND c.resourceTypeName = 'Organization'
AND c.isHistory = false
AND c.isDeleted = false
```
And we just specify how much is limit for max items in query settings.

If you know what release you had before (autumn 2020 is a bit vague) I can check what query used to be, but I doubt it was any different.

Main difference I can see between your output and mine is continuation token which cosmos return us back.

if I decode your continuation token it looks like this:
```
[{"token":null,"range":{"min":"05C1DFFFFFFFF8","max":"05C1E7FFFFFFFA"}}]
```
and 
```
[{"token":null,"range":{"min":"05C1E7FFFFFFFA","max":"FF"}}]
```

if I run it locally and in azure I get tokens which look like this:
```
[{"token":"+RID:~esE5ANcKvB8hBgAAAAAAAA==#RT:2#TRC:20#ISV:2#IEO:65567#QCF:3","range":{"min":"","max":"05C1D0"}}]
```
It looks like continuation token for you uses range filter, rather than token itself, and I honestly have no idea why.

We don't have much input on that token other than `CosmosDB:ContinuationTokenSizeLimitInKb` setting and I doubt it affect anything in your case.

Our query is quite simple and continuation token comes straight from cosmosdb, so not much we can screw up on our side.
About [10 months ago](https://github.com/microsoft/fhir-server/pull/1107) we switch to 3.* Cosmos SDK, but that's a bit earlier than Autumn 2020, so that doesn't sound like potential culprit.

Any chance you can run queries directly on your cosmos db?

this is query we use to determine total amount:
```
SELECT VALUE COUNT(1) 
FROM c
WHERE c.isSystem = false
AND c.resourceTypeName = 'Organization'
AND c.isHistory = false
AND c.isDeleted = false
```
This is query to iterate over all organizations:
```
SELECT c.id,c.isSystem,c.partitionKey,c.lastModified,c.rawResource,c.request,c.isDeleted,c.resourceId,c.resourceTypeName,c.isHistory,c.version,c._self,c._etag, c.searchParameterHash
FROM c
WHERE c.isSystem = false
AND c.resourceTypeName = 'Organization'
AND c.isHistory = false
AND c.isDeleted = false
```
This one should return you only first 100 results and option to get more, would it return all 2175 if you click load more until end?
If it doesn't return you results as expected, that's probably sign of something is going on with cosmos itself. If not, that's probably on us, but I can't think of anything other some weird serialization case where we drop things from bundle because bundle exceed some limit.

**Comment by ellgre** [comment]
I have tried the queries directly on cosmos db and both return the same total.
You have had the following fix https://github.com/Microsoft/fhir-server/commit/4ce798c5f8b9b523ba36d8cc49815f062969f280 between the version we were running before and now. Can this have changed anything?
We were running on Build 20200708-1 before.

**Comment by Ivanidzo4ka** [comment]
I think you are right, and I finally able to reproduce it locally.
I created resources sequentially with incrementing id, and I can see how some things got throw out from results:
![image](https://user-images.githubusercontent.com/1523833/117079589-ea6be480-acf0-11eb-9e0c-83ad5a2912a3.png)


Thanks for the tip!

**Comment by CaitlinV39** [comment]
AB#81893

**Comment by CaitlinV39** [comment]
@ellgre We have released a fix for this in this release: https://github.com/microsoft/fhir-server/releases/tag/release%2F2.0.18

**Comment by ellgre** [comment]
Thank your very much for fast reaction. Unfortunately we fould the following bug https://github.com/microsoft/fhir-server/issues/1916 when we tried to install the latest version.

**Comment by ellgre** [comment]
We have tested the new version and search now returns complete data.
