### ISSUE TITLE
Resource returned multiple times if it meets both base criteria and _include criteria

### ISSUE THREAD

**Issue by moiradillon12** [microsoft/fhir-server#2037]
**Describe the bug**
When running a search that has _include that meets the base criteria and also the include criteria, a single resource is included twice. Example: search for Locations and include partOF, which references a location, the location resource is returned twice. 

**FHIR Version?**
R4

**Data provider?**
CosmosDB

**To Reproduce**
1. Post a Location resource which references another Location resource with partOf.
2. Query : {{fhirurl}}/Location?_include=Location/partOf
3. Same Location resource will be returned twice 

**Expected behavior**
We expected a resource to only be returned once, even if it matches multiple criteria.

**Actual behavior**
Resource meeting multiple criteria is returned twice.

**Comment by CaitlinV39** [comment]
AB#84439

**Comment by CaitlinV39** [comment]
From Zulip on correct behavior:

I don't know of a place that it is specified cleanly, but the Constraints on bundle include a combination of rules that I believe force it:

fullUrl must be unique
fullUrl cannot be version specific
In the comments for Bundle.entry.search.mode, there is the line:

There is only one mode. In some corner cases, a resource may be included because it is both a match and an include. In these circumstances, 'match' takes precedence.

So, while well-hidden, match takes priority.

**Comment by mikaelweave** [comment]
Fixed in #2448
