### ISSUE TITLE
Searching by FHIR Resource extension

### ISSUE THREAD

**Issue by viku85** [Microsoft/fhir-server#219]
How can I search for extension values in FHIR Resource entries? I have registered SearchParameter based on **patient-extensions-Patient-mothersMaidenName** example from https://www.hl7.org/fhir. I assume that should show under FHIR Conformance which is not happening. I am trying to search through code(mothersMaidenName) or/and URL but it is resulting in getting all Patients (probably parameter is getting ignored).

**Comment by matjazl** [comment]
For number one, we currently don't support search on extensions, but it is on our roadmap.

"Another weird thing, I am seeing is if my parameter names while doing the search is not correct it is getting all the Resource items."

This is by design in FHIR spec. See https://hl7.org/fhir/2018May/search.html 

Unknown and unsupported parameters

Servers may receive parameters from the client that they do not recognize, or may receive parameters they recognize but do not support (either in general, or for a specific search). In general, servers SHOULD ignore unknown or unsupported parameters for the following reasons:

Various HTTP stacks and proxies may add parameters that aren't under the control of the client
The client can determine what parameters the server used by examining the self link in the return (see below)
Clients can specify how the server should behave, by using the prefer header

Prefer: handling=strict: Client requests that the server return an error for any unknown or unsupported parameter
Prefer: handling=lenient: Client requests that the server ignore any unknown or unsupported parameter
Servers SHOULD honor the client's request, but are not required to do so.

**Comment by jecihjoy** [comment]
Was the support for searching by resource extension added or still in your roadmap?

**Comment by hansenms** [comment]
You can add search parameters yourself on open source by modifying the `search-parameters.json` file (e.g. for R4 https://github.com/microsoft/fhir-server/blob/master/src/Microsoft.Health.Fhir.R4.Core/Features/Definition/search-parameters.json). The search parameters should be added before any new data is ingested and then they should get extracted. We are working on a better way to configure this and to do re-indexing if they are added after data has been ingested.
