### ISSUE TITLE
returned token same for fhir contributor as for not authorised fhir user

### ISSUE THREAD

**Issue by tomjscrypt** [microsoft/fhir-server#2234]
I have 2 users. User "A" is Fhir Contributor. User "B" is in same Active Directory as user "A" but is not authorised to access fhir resource server at all. They both pass login/authentication and receive proper token. As expected "A" can access server and "B" cannot. However I would expect user B to get some different token back, for example without "aud" attribute. Or best, instead of getting token I would expect to get "UnAuthorised" response from the server. Because when I declare scope I assume I am doing authentication not just for authentication but to access what is in the scope.
So will I always have to make that extra call and flag token as valid and then use it?

**Comment by CaitlinV39** [comment]
Hey @tomjscrypt I'm having a little bit of trouble following the issue. Can you use the following format to submit your issue? 

**Describe the bug**
A clear and concise description of what the bug is.

**FHIR Version?**
Stu3/R4/R5

**Data provider?**
CosmosDB/SQL Server

**To Reproduce**
Steps to reproduce the behavior:
1. 
2. 
3. 

**Expected behavior**
A clear and concise description of what you expected to happen.

**Actual behavior**
A clear and concise description of what actually happened.

**Comment by CaitlinV39** [comment]
@tomjscrypt - I'm going to close this for now but please feel free to reopen with more details.
