### ISSUE TITLE
Hosting options

### ISSUE THREAD

**Issue by dustinmoris** [microsoft/fhir-server#2370]
I have a question regarding the different hosting options for this project. The [official documentation is extremely confusing and weak](https://docs.microsoft.com/en-us/azure/healthcare-apis/) and this repository doesn't seem to have any meaningful documentation either so apologies for asking a very straightforward question like this.

How can I host this project?

Is there an official Docker image for the Microsoft FHIR API?
Is there a managed service in Azure for this?

The official documentation talks about deploying an App Service from the marketplace? That would mean that it's not a managed service right? So after the initial deployment I'd be left maintaining the app service myself in an old fashioned way?

Here is what I essentially want to achieve and I can't work out from this repo or the docs how to do it:

- I want a low maintenance way of hosting this API. If you release updates then I want to update my deployed API also in a low maintenance fashion (e.g. just changing the Docker image tag of my K8s manifest, or clicking a button in the Azure Portal to update to the latest version, or ideally just use a managed service where I don't have to do anything)
- I want to configure my own CosmosDb connection string and other connection strings which are needed even if it is a managed service. Is there any documentation on what data storage this needs and where to configure it?
- I want to run this API in a private network so I can put it behind a public proxy where I want to run existing authentication logic which I already have.

Any help in answering these questions would be much appreciated.

Thank you!

**Comment by brendankowitz** [comment]
Hi @dustinmoris,

Thanks for the feedback, I understand the confusion. Since you have a lot of questions / requirements I'll try to group your options.

Firstly there are two managed offering to be aware of:
1) Azure API for FHIR, our current GA product based on Cosmos
1) Healthcare APIs - FHIR Service - our preview product based on the SQL backend

Questions
- I need private link:
  - Managed options
    - Azure API for FHIR is the only option right now (https://docs.microsoft.com/en-us/azure/healthcare-apis/azure-api-for-fhir/fhir-paas-portal-quickstart and https://docs.microsoft.com/en-us/azure/healthcare-apis/azure-api-for-fhir/configure-private-link)
  - OSS
    - If you deploy to AppService you can configure privatelink yourself there: https://github.com/microsoft/fhir-server/blob/main/docs/DefaultDeployment.md
- Is there an official docker image:
  - We push our OSS builds to Dockerhub via MCR (Microsoft Container Registry): https://hub.docker.com/_/microsoft-healthcareapis-r4-fhir-server
- I want to configure my own CosmosDb connection string and other connection strings which are needed even if it is a managed service
  - You cannot configure connection string in the managed service, if you want this control your only option is OSS. Managed service takes care of more security features such as Key rotations and autoscaling compute based on configured database size.
- I want a low maintenance way of hosting this API
  - We put a lot of work into making this happen smoothly for the managed service
  - If deploying OSS with a docker image, you should be able to update the tag to a later release: https://github.com/microsoft/fhir-server/releases

**Comment by CaitlinV39** [comment]
@dustinmoris - Let us know if you have other questions.
