### ISSUE TITLE
Directly query source tables in SQL Server

### ISSUE THREAD

**Issue by unruledboy** [microsoft/fhir-server#2476]
**Question**

How to directly query source tables in SQL Server rather than the ones got extracted / persisted by FHIR server.

**Description**

Our medication system has existing complex data structures (tables) in SQL Server. Now that we want to support FHIR.

After reading documentations and going through the codebase, take the search for example, `SqlServerSearchService `builds the sql that tailored for its own data table structures based on the query expression.

But we think having a process in place to extract and persist into the table structures is somehow quite challenging and clumsy:
- It's likely not real-time, even it's real-time, it could hurt the performance (whenever there is piece of data changed)
- And the logic to work out what needs to be extracted/persisted could be quite complicated

Is there a practice / guidance in place to allow the developers to write their own logic to pull data out of their existing data tables that conforms with `SearchService`, effectively a drop-in replacement of the existing `SqlServerSearchService`?

**Comment by Ivanidzo4ka** [comment]
>Now that we want to support FHIR.

There is more than just a search capability, at least from our perspective, we need to accept data, we need to provide information about what our server can and cannot do, we need to support different operations, FHIR spec is long and full of pesky details we had to care about.

If you looking for just supporting FHIR search on top of your existing data, I would suggest to take Firely library and implement adapter on top of your data. Our project does a bit more than that, and in order to support FHIR,  we had to go the road of complex hierarchy and certain assumptions which maybe not align with your desires :)

We support two different persistent layers right now: CosmosDB and SqlServer, one is document based storage, another is relationship database, and if you looking for full FHIR support, you basically need to implement your own project with custom implementations for certain interfaces
https://github.com/microsoft/fhir-server/blob/a2eb81ddf251555d5cc72ddf568945163875daf9/src/Microsoft.Health.Fhir.Shared.Api/Modules/PersistenceModule.cs#L33

Which would require not only search, but opportunity to ingest data into your persistent layer via "our" API.

And I'm not sure this is what you looking for...

**Comment by unruledboy** [comment]
@Ivanidzo4ka  you are spot on. Besides search, down the track, we need to accept FHIR request so that it can also upsert data into our current SQL Server.

To simply put:
1. If we do want to leverage our existing table structures, we will need to implement our own ISearchService (is any doc about it or we just need to do like what SqlServerSearchService  is doing?)
2. If we don't want to struggle too much with implementing our own search/ingest logic, there is still a question on how to "sync" our data into FHIR tables?

**Comment by fasteddys** [comment]
Hello where is the FHIR schema for SQL server... I have been looking and cant find it

**Comment by unruledboy** [comment]
\fhir\src\Microsoft.Health.Fhir.SqlServer\Features\Schema\
