### ISSUE TITLE
"New-FhirServerApiApplicationRegistration.ps1" fails due the the new app registration not specifying an identifierUri matching the verified domain or subdomain of "the organization"

### ISSUE THREAD

**Issue by olabma-bit** [microsoft/fhir-server#2555]
### Discussed in https://github.com/microsoft/fhir-server/discussions/2216

<div type='discussions-op-text'>

<sup>Originally posted by **CaitlinV39** September  8, 2021</sup>

## 👋 Welcome to the Microsoft FHIR Server discussion page
  We’re using Discussions as a place to connect with other members of our community. We're hoping that this will be a good place for discussions around the use of our specific implementation of the FHIR service. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community. We hope this will supplement the http://chat.fhir.org which is the official community space for FHIR questions. 

We have documentation on the open-source site and additional documentation on our managed service here: https://docs.microsoft.com/azure/healthcare-apis/fhir/

</div>

**Comment by olabma-bit** [comment]
Hi All,
I run into this error while trying to complete (https://microsoft.github.io/WhatTheHack/027-FHIRPoweredHealthcare/Student/Challenge01.html)
"Ensuring API application exists
New-AzureADApplication: /home/xxxxxxx/fhir-server-samples/deploy/scripts/fhir-server-main/samples/scripts/PowerShell/FhirServer/Public/New-FhirServerApiApplicationRegistration.ps1:69
Line |
  69 |  … apiAppReg = New-AzureADApplication -DisplayName $FhirServiceAudience  …
     | Error occurred while executing NewApplication  Code: Request_BadRequest Message: Values of identifierUris property must 
     | use a verified domain of the organization or its subdomain:
     | 'https://rgfhrsvr.azurehealthcareapis.com' RequestId: 21332ac6-138d-4e61-8515-ef4015b52a09 DateTimeStamp: Wed, 13 
     | Apr 2022 22:04:11 GMT Details: PropertyName  - identifierUris, PropertyErrorCode  -
     | HostNameNotOnVerifiedDomain, HostName  - https://<environment>.azurehealthcareapis.com HttpStatusCode: BadRequest 
     | HttpStatusDescription: Bad Request HttpResponseStatus: Completed"

PropertyNotFoundException: /home/xxxxxx/fhir-server-samples/deploy/scripts/fhir-server-main/samples/scripts/PowerShell/FhirServer/Public/New-FhirServerApiApplicationRegistration.ps1:70
Line |
  70 |      New-AzureAdServicePrincipal -AppId $apiAppReg.AppId | Out-Null
      |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'AppId' cannot be found on this object. Verify that the property exists.

PropertyNotFoundException: /home/xxxxx/fhir-server-samples/deploy/scripts/fhir-server-main/samples/scripts/PowerShell/FhirServer/Public/New-FhirServerApiApplicationRegistration.ps1:76
Line |
  76 |      @{
       |      ~~
       | The property 'AppId' cannot be found on this object. Verify that the property exists.

It appears an attempt to create an An App Registration for FhirServer  as specified in the Powershell script named: "New-FhirServerApiApplicationRegistration.ps1" fails due the the new app registration not specifying an identifierUri matching the verified domain or subdomain of  "the organization"  

Has anyone encountered the same problem?

**Comment by adm-kduddu** [comment]
Same issue , Any resolution please

**Comment by aidanplunkitt** [comment]
Hi @adm-kduddu and @olabma-bit, it looks like this is an issue with [a breaking change in Azure AAD from October](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-breaking-changes#appid-uri-in-single-tenant-applications-will-require-use-of-default-scheme-or-verified-domains) in how they expect the Identifier URIs to be formatted. A quick fix would be to change a few lines after attempting to run the `Create-FhirServerSamplesEnvironment.ps1` (it must be run after so that [the `fhir-server` archive is fetched and expanded](https://github.com/microsoft/fhir-server-samples/blob/master/deploy/scripts/Create-FhirServerSamplesAuthConfig.ps1#L67), since a file from that repository needs to be edited as well).

- [deploy/scripts/Create-FhirServerSamplesAuthConfig.ps1:133](https://github.com/microsoft/fhir-server-samples/blob/master/deploy/scripts/Create-FhirServerSamplesAuthConfig.ps1#L133) -> replace `https` with `api`
- [deploy/scripts/Create-FhirServerSamplesAuthConfig.ps1:135](https://github.com/microsoft/fhir-server-samples/blob/master/deploy/scripts/Create-FhirServerSamplesAuthConfig.ps1#L135) -> same as above, in the case that you use the PaaS configuration (`-UsePaas $true`)
- [deploy\scripts\fhir-server-main\release\scripts\PowerShell\FhirServerRelease\Private\SharedModuleFunctions.ps1:63](https://github.com/microsoft/fhir-server/blob/main/release/scripts/PowerShell/FhirServerRelease/Private/SharedModuleFunctions.ps1#L63) -> same as above, replace `https` with `api`

Let me know if this works for you. It allowed me to successfully run through the [fhir-server-samples deployment](IdentifierUris) and I was able to successfully [get the /metadata endpoint from the created webapp](https://github.com/microsoft/fhir-server/blob/main/docs/QuickstartDeployPowershell.md#verify-fhir-server-is-running), although I didn't try to continue with the WTH challenge beyond that.

**Comment by adm-kduddu** [comment]
With the above fix no need to add company domain ? Just use exsisting ones and follow above steps ?
________________________________

**Comment by aidanplunkitt** [comment]
Yes that's correct, I tested a fresh clone only making those specified changes and it seemed to do the trick.

**Comment by adm-kduddu** [comment]
Awesome !! Let me test that in a bit
________________________________

**Comment by adm-kduddu** [comment]
Install is success but no patient data is loading in dashboard .Can you please help ..

***@***.***

**Comment by adm-kduddu** [comment]
@aidanplunkitt No issues with , I was able to login to web app but patient data is struck on loading .. Any idea ?

![image](https://user-images.githubusercontent.com/105236310/167975276-4948d2ff-ae6f-41b4-b86d-6d4d0506f83f.png)

**Comment by aidanplunkitt** [comment]
I looked further into the [WTH tutorial](https://microsoft.github.io/WhatTheHack/027-FHIRPoweredHealthcare/Student/Challenge01.html) and it isn't particularly clear on steps required to set up auth correctly for the app. The information may be a bit stale since it looks like that was authored over a year ago. For a more actively maintained tutorial, I'd recommend going through [this workshop](https://github.com/microsoft/azure-health-data-services-workshop/) which uses a managed FHIR API on Azure to walk you through a similar set of challenges. If you want to set up your own deployment using the OSS build then there are [quickstart docs](https://github.com/microsoft/fhir-server/blob/main/docs/QuickstartDeployPowershell.md) to deploy to Azure, as well as docs for [getting a server running locally](https://github.com/microsoft/fhir-server/tree/main/samples/docker).

**Comment by mikaelweave** [comment]
Agree with @aidanplunkitt - closing for now. Please re-open if you need any more help! 👍🏽
