### ISSUE TITLE
Deploy FHIR server on an existing SQL managed instance

### ISSUE THREAD

**Issue by msmtctaiwan** [microsoft/fhir-server#2606]
**Question**
Is there any reference to deploying the FHIR server on an existing SQL managed instance with an endpoint?

**Comment by LTA-Thinking** [comment]
Hi @msmtctaiwan 
We do not have any documentation on this because it is easy to mess up a FHIR server by changing or removing certain resources in the database, but if you want to connect the OSS FHIR server to your own SQL instance it is doable. 
After deploying an instance using one of our [quickstart](https://github.com/microsoft/fhir-server/blob/main/docs/QuickstartDeployPortal.md) methods with the SQL options you can go into the key vault that was made for the FHIR server. Inside it is a secret called SqlServer--ConnectionString. Update this secret with the connection string for the SQL server you wish to connect to and the FHIR server will use it instead of the one it was provisioned with.
You will need to restart the webapp for this change to take effect, and I would recommend the webapp be stopped while making this change.
When the webapp is restarted it will start making changes to the SQL database to enable FHIR to work. This will include making tables, data, and stored procedures. So long as there isn't a name collision this shouldn't affect your existing data. After this startup is complete your FHIR server should be ready to use, and you can delete the SQL server that was provisioned with the FHIR server.
@rbans96

**Comment by msmtctaiwan** [comment]
Hi @LTA-Thinking 
Thanks for your kind support and fast response. I still have a few questions. 
Is it possible to deploy FHIR on Azure stack HCI and migrate with Arc enabled SQL Managed instance? To the best of my knowledge, Arc-enabled SQL managed instance does not provide a connection thus it is infeasible to change the connection string in the key vault we just deployed using quickstart.
I would be grateful if you could provide some thoughts/comments on deploying the FHIR server on Azure Stack HCI. 
Thanks!

**Comment by LTA-Thinking** [comment]
Hi @msmtctaiwan 
I'm afraid this is outside the scope of the our open source solution. Integration with HCI may require a new database connection type, or a more complicated service setup. Either of these is outside the limited support we offer for the open source solution. My best recommendation would be to reach out to someone more familiar with Azure Stack HCI and Arc enabled SQL to see if a workaround could be setup to get a connection string.

**Comment by msmtctaiwan** [comment]
Hi Robert-
I will reach out to the HCI team for more information. Thanks!
