### ISSUE TITLE
Searching on gender gives error

### ISSUE THREAD

**Issue by Sameer2810** [microsoft/fhir-server#3596]
**Describe the bug**
When combined ImagingStudy and Patient and try to search on patient gender then it gives following error

**FHIR Version?**
R4

**Data provider?**
CosmosDB

Following is screen shot for that

![image](https://github.com/microsoft/fhir-server/assets/38692494/af70dcf0-f45f-4bf9-8046-cd6e9ffffe76)

**Comment by brendankowitz** [comment]
Hi @Sameer2810, this is more of a known limitation with Cosmos. We did document this behavior here: https://learn.microsoft.com/en-us/azure/healthcare-apis/azure-api-for-fhir/overview-of-search#chained--reverse-chained-searching. Since the "join" logic happens in code, the implementation recurses to the end of the chain the pulls the filter up, if any level of the chained search exceeds 1000 rows it stops the execution. 
Queries with large joins work ok with Health Data Services / SQL.

**Comment by EXPEkesheth** [comment]
@Sameer2810 closing this issue with known limitation on Cosmos DB persistence layer
