### ISSUE TITLE
Support SQL Server as a data provider

### ISSUE THREAD

**Issue by johnstairs** [microsoft/fhir-server#400]

**Comment by justinbhopper** [comment]
@jackliums @johnstairs I'm curious if there are any guesses how well the SQL Server persistence layer might perform in comparison to the Cosmos solution?  

I'm guessing adding support for SQL Server is mostly driven from a desire to increase support/compatibility, and not because it is believed it will become the superior data storage medium for fhir-server, but I'm just speculating...

**Comment by hansenms** [comment]
The SQL persistence provider is being implemented to support features such as chained searches, _include, _revinclude, transactions, etc. These things are hard to support using Cosmos. Hope this helps.

**Comment by hansenms** [comment]
It is available for SQL now.
