### ISSUE TITLE
Some search paramter can be skipped when invalid is supplied but some should not.

### ISSUE THREAD

**Issue by jackliums** [microsoft/fhir-server#430]
**Describe the bug**
Some parameter should not be skipped and ignored when the value is not valid.

**To Reproduce**
1. Search `/Patient?_count=0`

**Expected behavior**
The search should fail with 400 Bad Request.

**Actual behavior**
The search succeeds and _count parameter is ignored. This is returned in the self link of the bundle. However, since the client is specifying a specific number, if that cannot be fulfilled, we should not potentially return more than the client has asked.

**Comment by CaitlinV39** [comment]
Per the spec for FHIR V 4. if _count has the value 0, this shall be treated the same as _summary=count: the server returns a bundle that reports the total number of resources that match in Bundle.total, but with no entries, and no prev/next/last links.

@jackliums the expected behavior on this bug doesn't match the spec. Do you want to modify or we can close?
