### ISSUE TITLE
Unstable E2E test: HistoryTests(CosmosDb, Xml).WhenGettingSystemHistory_GivenAValueForSinceAndBeforeCloseToLastModifiedTime_TheServerShouldNotMissRecords

### ISSUE THREAD

**Issue by johnstairs** [microsoft/fhir-server#475]
See https://microsofthealthoss.visualstudio.com/FhirServer/_releaseProgress?releaseId=1093&environmentId=2426&_a=release-environment-logs

Error message
Assert.Equal() Failure
Expected: 4
Actual: 0

Stack trace
   at Microsoft.Health.Fhir.Tests.E2E.Rest.HistoryTests.WhenGettingSystemHistory_GivenAValueForSinceAndBeforeCloseToLastModifiedTime_TheServerShouldNotMissRecords() in D:\a\1\s\test\Microsoft.Health.Fhir.Tests.E2E\Rest\HistoryTests.cs:line 173
--- End of stack trace from previous location where exception was thrown ---

**Comment by feordin** [comment]
There may be an underlying issue with Cosmos DB that makes some of the history tests unreliable.  Also this crucible test: "history001/HI09" has been failing.  This Crucible test has been added to our list of known failures.  Once this issue is fixed the list in CrucibleTestFixture.cs should be modified to start running the "history001/HI09", test once again.
