### ISSUE TITLE
Upsert functionality doesn't return newly created resource

### ISSUE THREAD

**Issue by devcs21** [microsoft/fhir-server#579]
**Describe the bug**
src\Microsoft.Health.Fhir.Shared.Core\Features\Resources\Create\CreateResourceHandler.cs
method: Handle
1) it takes original resource from request
`var resource = message.Resource.Instance.ToPoco<Resource>();`
2) it calls await `FhirDataStore.UpsertAsync`
3) then return back original document, not created one (in which backend already set some custom data like internal ids/meta data/versioning/links to other  necessary resources etc)

`return new UpsertResourceResponse(new SaveOutcome(resource.ToResourceElement(), SaveOutcomeType.Created));`

**To Reproduce**
1. send any create request from postman/fiddler/xunit test method 
2. look at returned document -> it's the same

**Expected behavior**
created document not original one but contains data from backend (internal ids/meta data/versioning/links to other necessary resources etc)

**Actual behavior**
original document without information from backend

possible fix (our current workaround):
replace 
`return new UpsertResourceResponse(new SaveOutcome(resource.ToResourceElement(), SaveOutcomeType.Created));`

with

`var jsonParser = new FhirJsonParser();`
`var upsertResource = (Resource)jsonParser.Parse(result.Wrapper.RawResource.Data);`
`upsertResource .VersionId = result.Wrapper.Version;`

`return new UpsertResourceResponse(new SaveOutcome(upsertResource .ToResourceElement(), SaveOutcomeType.Created));`

**Comment by jackliums** [comment]
Do you have a specific example what data is missing?

I think the only thing we are generating in the BE is the version, which we copy back to the resource after the database operation in CreateResourceHandler. The meta and lastUpdated date is generated in the FE so that information already exists in the resource. I think it was implemented this way to avoid additional deserialization. 

There are some E2E test covering this scenario in UpdateTests.cs which tests to make sure the VersionId and LastUpdated are correct after the update.

We might refactor this logic if we start populating more data in the BE.

**Comment by BertilReppen** [comment]
As an example:
If a FHIR client creates a new Patient on a backend, server will create a unique ID for  the Patient.
if server just returns back the original "resource" we have no access to de ID of the resource.
There can also we other modifications the server could make on the created resource, and we also need that information.
if server just returns back the original "resource" how can we request for this Patient in the future if we don't have his ID? We don't get access to his ID. 
if server returns modified resource (like in workaround above) the fhir client will get all necessary information (including IDs) to request  this Patient.

**Comment by hansenms** [comment]
@BertilReppen, if you `POST` a resource to the FHIR server and the server generates and id, we will return the resource to you. It does not "return back the original resource". 

See for example: https://docs.microsoft.com/en-us/azure/healthcare-apis/access-fhir-postman-tutorial#inserting-a-patient

If you have a repro case where that does not happen, please include it so that we can test.

**Comment by devcs21** [comment]
@hansenms
your team created a really great architecture that encourages people to use this fhir server to expose their already existing databases with fhir endpoints.

so, let's look at following cases:
**case 1)** someone uses MS FHIR server "as is", uses it automatically generated DB structure like Resource table, ResourceType table etc
so, devs relies on ID's generation that's inside Microsoft.Health.Fhir.Core.Features.Resources.BaseResourceHandler.cs
line 41:
```
if (string.IsNullOrEmpty(resource.Id))
            {
                resource.Id = **Guid.NewGuid().**ToString();
            }
```

there is nothing special here.

**case 2)** There is already some mature Healthcare organization. There is already some SQL database with tables Patient, Organization, CommunicationRequest etc
there are already dozen of stored procedures etc etc
so, it's impossible to use your cosmosdb workflow, or your implementation of SQL Server's workflow
but, you developed a great architecture that allows to create any custom implementation of IFhirDataStore and inject it to MS FHIR server workflow by using DI.
so, the fact is that people already extends your fhir server with their custom implementation of IFhirDataStore and they will do it in the future also.

from this point of view:
a)  your need to move assigning of "GUID id" from BaseResourceHandler.cs to concrete datastores:
- Microsoft.Health.Fhir.SqlServer.Features.Storage.SqlServerFhirDataStore
- Microsoft.Health.Fhir.CosmosDb.Features.Storage.CosmosFhirDataStore

b) existing Healthcare organization use own rules to assign IDs, they may be GUIDs, may be long, int, or some custom composite string key etc
you really have no idea how id will be generated.

c) you store a fhir resource as "raw resource" in Resource table. But, existing old Healthcare organization could use the following workflow:
fhir client-> fhir document(resource)-> ms fhir controller -> Custom implementation of IFhirDataStore -> SQL database.

and you have no idea what's going on inside "custom implementation".
which IDs will be assigned. Which other properties will be modified.
may be this custom impl. just takes original document -> parses it, extracts data, store these data in custom tables but with concrete fields/columns (id, name, address etc) , not as a "raw resource",

and then creates a custom fhir document(resource) by using some third-party library or own similar library and returns to ms fhir server's workflow not original but somehow created valid FHIR resource.

you can not rely on that FhirDataStore.UpsertAsync always return original document just with few properties modified.
it may return completely new document with some properties from original document, some properties will be generated somehow in BE etc.

so, workaround above (with deserialization) will cover both cases:
1) using standard ms fhir workflows (cosmosdb or storing in ms sql server as "raw resource")
2) using some custom implementation of IFhirDataStore, where original document won't be "touched" but newly created document will be returned.

P.S. generally speaking, original resource should be "immutable".

**Comment by hansenms** [comment]
@brendankowitz

**Comment by brendankowitz** [comment]
I think we're summarizing that you'd like the code work also work as a FHIR Server facade for some existing datastore. This wasn't a design consideration initially, which is why we opted to avoid the extra deserialization work.

I think your best option right now is to use your own implementation of CreateResourceHandler, which could be done by overriding the registration:

```
services.Add<MyCreateResourceHandler>()
    .Transient()
    .ReplaceService<IRequestHandler<CreateResourceRequest, UpsertResourceResponse>>();
```

I can imagine there would be a collection tasks that would fall under the banner of 'allowing the FHIR Server to work with existing underlying datastores', including the use-cases you've outlined. I might leave this to @hansenms to see if or how we want to track such a feature.

**Comment by hansenms** [comment]
Closing this since much work has been done to make it easier to implement a custom persistence provider and there are no specific work items related to this.
