### ISSUE TITLE
ArgumentException() thrown when search request contains "-_count"

### ISSUE THREAD

**Issue by jackliums** [microsoft/fhir-server#580]
**Describe the bug**
We have an unhandled exception during the GET Fhir/SearchByResourceType request flow. It ends up in a 500 response code. Seems like the incoming request contains a "-_count" parameter that is not a valid SearchParams.

**To Reproduce**
1. Search by using `Patient?_summary=_count`

**Expected behavior**
400 Bad Request should be thrown.

**Actual behavior**
500 Internal Server Error is thrown.

**Comment by brendankowitz** [comment]
Should it be valid to use the int value of the enum? For instance `/Observation?_summary=3` is the same as `/Observation?_summary=count`. `/Observation?_summary=100` can be used, but is ignored.

**Comment by brendankowitz** [comment]
Lets also add that using numeric values should also result in a 400

**Comment by brendankowitz** [comment]
A 500 is also thrown when executed against the metadata endpoint:
https://msh-fhir-ci-r4.azurewebsites.net/metadata?_format=json&_summary=xyz

**Comment by Ivanidzo4ka** [comment]
Do you mind if I take care of this one?

One thing which comes to my mind when I'm looking into current code and why it's happening it looks like main problem is in absence of validation for query parameters.
From what I see query parameters just get passed down to search without much of validation.
https://github.com/microsoft/fhir-server/blob/00d18530cdcdd2e2a56afe6a24455a4d3149e76a/src/Microsoft.Health.Fhir.Shared.Api/Controllers/FhirController.cs#L417

Is there are reason to push that to search itself instead of doing basic validation through model binding?
Would it be beneficial to have strongly typed object instead of `IReadOnlyList<Tuple<string, string>> queries` or strings give project some flexibility?

**Comment by CaitlinV39** [comment]
AB#76055
