### ISSUE TITLE
How do I access the Cosmos DB instance when I provision an instance of Azure API for FHIR?

### ISSUE THREAD

**Issue by sdg002** [microsoft/fhir-server#750]
**User story**
Firstly, thank you so much for open sourcing Microsoft's FHIR implementation. We are a healthcare starup based out of London. We are looking at using **Azure API for FHIR** down the road.  I was able to provision Azure API for FHIR using the portal and configure Active Directory authorization. Also able to use POSTMAN to add Patient and Observation records.

**Question**
How do I access the underlying **CosmosDB** instance where all this information is being written?

Thanks,
Saurabh

**Comment by hansenms** [comment]
When running the Azure API for FHIR, the data layer is an implementation detail and Microsoft is responsible to maintaining that. Since Microsoft assumes responsibility for the data layer, there cannot be direct access to it. 

If you would like to have direct access to the data layer, we recommend you run the OSS version where you can manipulate the database directly and modify the code. That said, we do not recommend taking any dependencies on the specific database scheme. It should be considered an implementation detail.

Another note, questions about the Azure API for FHIR are best routed through the docs.microsoft.com pages or stackoverflow where we will try to answer.

**Comment by sdg002** [comment]
Thank you.
