### ISSUE TITLE
Information about Azure costs

### ISSUE THREAD

**Issue by bobosette** [microsoft/fhir-server#758]
Hi everybody. I would like to know how much does this open source azure fhir server cost !
When I set up everything in the Azure portal I have this group of resources:
- AppInsights
- Account Azure Cosmos DB
- Credentials and key
- App service
- App service plan
plus the Fhir API service.

How much for this solution monthly?
I ask here cause on the portal i can't find an answer (also with the costs calculator)

Thank u

**Comment by hansenms** [comment]
Can you clarify how the cost calculator is not working for this? You should be able to go to: https://azure.microsoft.com/en-us/pricing/calculator/ and put in Cosmos DB and App Service (those would be the two main things you would be paying for). The cost calculator will also provide information for the managed Azure API for FHIR. You can also open the resource group and hit the cost analysis for specifics on the deployment you are running:

![image](https://user-images.githubusercontent.com/1149740/69337926-5de77680-0c62-11ea-8dde-b855e6cfb9fc.png)

For now, I am going to close this issue, since this is not really the right forum for Azure pricing.
