### ISSUE TITLE
Fhir API c# Smart authentication on Azure fhir server

### ISSUE THREAD

**Issue by bobosette** [microsoft/fhir-server#759]
Hi. As I already wrote I setted up Smart for Fhir authentication on my server, following this guide https://docs.microsoft.com/en-us/azure/healthcare-apis/use-smart-on-fhir-proxy . Now I have a web app with Visual Studio and I'm using this API https://github.com/FirelyTeam/fhir-net-api to working on the DB with c#.
How can I obtain the access token with my web app? I didn't find any guide about this using c#.
Thank u

**Comment by hansenms** [comment]
There is some guidance on the SMART on FHIR proxy here:

https://docs.microsoft.com/en-us/azure/healthcare-apis/use-smart-on-fhir-proxy

And in the docs pages you will also find more information on authentication scenarios, etc.

I am closing this issue here since it doesn't pertain to the source code for the FHIR server. Please use the docs pages to ask questions. And also look at the questions that have already been answered there.
