### ISSUE TITLE
Authentication with SMART: Roles

### ISSUE THREAD

**Issue by bobosette** [microsoft/fhir-server#787]
Hi everybody. In the app's manifest that I registered in Azure AD I setted up user's roles
![Cattura](https://user-images.githubusercontent.com/13197553/70794853-ea3b1400-1d9e-11ea-9987-9216fa1587b6.PNG)

Then I do all the stuff to abtain the access token to make calls to the server, and in the token there are the roles correctly.
My question is: why only the admin role can access the server, and the patient role can't (I get this response)?
![Cattura](https://user-images.githubusercontent.com/13197553/70795074-51f15f00-1d9f-11ea-9840-eab7460abe3b.PNG)

Cause I would like to let admin do everything, and patient maybe do only GET request (read operations), but where I can set this?
The scope I defined for the app is https://xxxxxx.azurewebsites.net/User.Read

Thank you

**Comment by hansenms** [comment]
Few comments:

Scopes are not enforced at this point, so that is not relevant. 

I am assuming this is with the OSS server (not the managed service, where roles are not used). Have you defined a patient role on the server? This is done with application settings. The default template only defines a single (admin) role: https://github.com/microsoft/fhir-server/blob/master/samples/templates/default-azuredeploy.json#L108 but you can add more (either to the template or by setting app settings after deployment).

**Comment by bobosette** [comment]
Thank u. Looks like the answer I was searching for. Now I try!

Il Ven 13 Dic 2019, 16:38 Michael Hansen <notifications@github.com> ha
scritto:
