### ISSUE TITLE
Support for PostgreSQL

### ISSUE THREAD

**Issue by cristianrablau** [microsoft/fhir-server#800]
It would be really nice to support PostgreSQL as an open source storage option besides CosmosDB and SQL Server. 

Would it be hard to integrate a new provider for PostgreSQL?

**Comment by hansenms** [comment]
The short answer is that it would be significant work to build a postgesql provider.

It might be worth understanding what your use case is? Could you elaborate on what specific functionality you are looking to enable?

The reasons for asking is that the SQL schema is not a bunch of tables that reflect the FHIR data structures, i.e. there is no Patient table or Observation table. It is really optimized for serving FHIR searches, so we store tables of search parameters (based on their types). When people talk about postgresql, it is usually because the want to leverage features in that database to query the data directly in ways that are maybe more natural with postgresql. To accomplish something like that would be even more work than just enabling what we do now in postgresql, it would be a completely different way of storing data and serving FHIR searches.

**Comment by cristianrablau** [comment]
Thanks for your answer. I have no specific use case. I was just thinking of PostgreSQL as a free alternative to SQL Server 😄

**Comment by hansenms** [comment]
OK, fair point. We would probably not implement a postgresql provider just because it is "free". Nothing really is. It may be free of license costs, but there are other costs of course. That is probably a discussion best left for others.

It is "free" to run SQL server for development purposes and in Azure the license cost is baked in, so it should at least be possible to work with the SQL implementation.

**Comment by granadacoder** [comment]
Is there a provider model already in play to make this an option for "the community"?  I would not expect MS to do this work, but it would be nice to have a code structure that would allow for a future sql-maker for a different RDBMS.

**Comment by hansenms** [comment]
Yes, the persistence layer is abstracted out in a persistence provider and a search provider and you can build your own. @brendankowitz demonstrated this at the last dev days. The best way to get started is to look at the interfaces that the current persistence providers implement. The persistence providers also communicate the capabilities to the capability statement so make sure that it only publishes what you would be able to support on your persistence provider.

**Comment by hansenms** [comment]
We have no plans for PostgreSQL, so I am closing this.

**Comment by granadacoder** [comment]
(This is my opinion on it......)

For the original reader.  This project is not a traditional "ORM" type of project.
For Ms Sql Server, the team is using (many? but important) Ms Sql Server specific features to get PERFORMANCE.
A traditional "chatty" ORM would never work here.  Or would run horribly.

This is why a "portover" would be a full fledged and very intense project.

CTE's are the one I see the most.

https://docs.microsoft.com/en-us/sql/t-sql/queries/with-common-table-expression-transact-sql?view=sql-server-ver15
