### ISSUE TITLE
not able to search all matching value with all resources(_type) FHIR Server

### ISSUE THREAD

**Issue by rameshkr1994** [microsoft/fhir-server#837]
Hi @hansenms 

we are trying to search identifier value with _type=Patient,Medication,CareTeam etc...

below is the search query:- 
`https://opensfhir.azurewebsites.net/?_type=Patient,CareTeam&identifier=549&_format=application/json`

but above query is fetching all identifier value from Patient and CareTeam that is matching and non matching value from both resources.

But we want to fetch only matched identifier value with "549"only(similar to where condition with all resources)

Note:-is there any simple code or demo to  search the value w.r.t to all resources ?

Please correct me?

Thanks
HadoopHelp

**Comment by hansenms** [comment]
`identifier` is not an accepted search parameter at the root endpoint, since not all resources have an `identifier` that can be searched. If you check the `self` link you when doing that search you will notice that `identifier` has been stripped from the search string indicating that it is not an accepted search parameter. This is standard behavior, please see the "Unknown and unsupported search parameters" section here': https://www.hl7.org/fhir/search.html.

If you want to do that search, do two searches, one on Patient and one on CareTeam. 

Closing this, since it is not an issue with the FHIR server. Please direct all general FHIR questions to https://chat.fhir.org or https://stackoverflow.com/questions/tagged/hl7-fhir. The issues here should really focus on bugs and features directly related to the Microsoft FHIR server for Azure.
