### ISSUE TITLE
How to create a SWAGGER Instance for all available Resources

### ISSUE THREAD

**Issue by ToperCarlos** [microsoft/fhir-server#844]
**User story**
As a developer, I want to view a SWAGGER so that i can view all available resources under FHIR.

**Acceptance criteria**
1. When I do hit a swagger URI, then view all Resources that are available.

**Comment by rameshkr1994** [comment]
use below link:-

https://fhir2apim.azurewebsites.net/



Thanks
HadoopHelo

**Comment by cristianrablau** [comment]
@ToperCarlos I think this is not possible. The 'generic' way the server is implemented does not allow you to see all the resources with Swagger. You can take a look into FhirController.cs to see the available operations. 

You can still see all the capabilities of a server by calling /metadata on any FHIR server. This will give you a [CapabilityStatement](https://www.hl7.org/fhir/capabilitystatement.html) resource.

**Comment by hansenms** [comment]
The FHIR server does not produce a swagger definition, but there are some tools that try to turn the capability statement into a swagger definition. The one pointed out to @rameshkr1994 is a start, but incomplete since it does not produce schemas for the data types. It does enumerate all the endpoints.

We have some separate workstreams on this, but I will close this issue since it is not a requirement for the FHIR server.
