### ISSUE TITLE
an we do linking/referencing/Compartment(relation) after loaded data in FHIR SERVER

### ISSUE THREAD

**Issue by rameshkr1994** [microsoft/fhir-server#849]
Hi @hansenms 

we have a huge flat JSON data in form of FHIR Server but there is not linking/referencing/Compartment (Relation) with all resources.

can we do linking/referencing/Compartment after loaded data in FHIR SERVER like:-

for Patient :- put Patient-Compartment-Definition 
for Encounter :- put Encounter Compartment-Definition
for CareTeam :- put CareTeam Compartment-Definition
..
...
.....
so on.

we want to provide linking/referencing/Compartment with already data loaded with FHIR SERVER.

is there any way of providing Compartment-Definition for each resources ?

because we are  putting sql server(on-premise ) data to FHIR SERVER using python code and database team are not able to provide linking/referencing/Compartment within sql server.

Thanks
HadoopHelp

**Comment by hansenms** [comment]
I am having a very hard time understanding this question. This is a basic FHIR question, I think, not related to this specific FHIR server. 

FHIR compartments are predefined by the FHIR spec:

https://www.hl7.org/fhir/compartmentdefinition.html

And as it says: "At present, compartment definitions can only be defined by HL7 International. This is because their existence creates significant impact on the behavior of servers.", so you should not be attempting to configure our own compartment.

Links between resources is a different matter. If you provide appropriate references, e.g. `Observation.subject.reference=Patient/1234` and you insert the Patient resource with `id`=123` using Upsert semantics, they will be linked.

Closing this issue since it is not related to this FHIR service.

> Please ask general FHIR questions on either Stackoverflow (https://stackoverflow.com/tags/hl7-fhir) or https://chat.fhir.org.

**Comment by rameshkr1994** [comment]
Hi @hansenms .

Thank you very much...

I understood now.


Thanks
HadoopHelp
