### ISSUE TITLE
FHIR deployment failing with .net core version mismatch error

### ISSUE THREAD

**Issue by vishnu-anil** [microsoft/fhir-server#868]
Earlier when i does the FHIR deployment using the Azure provided template "Click and deploy to azure", it used to create all required resources and deploys FHIR. But now i see
1. It just deploys the resources and do not performs a deployment.
2. When i go to the App service Deployment center and performs an External Git deployment, the deployment fails with the below error.

`Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling ASP.NET Core Web Application deployment.
A compatible installed .NET Core SDK for global.json version [3.1.100] from [D:\home\site\repository\global.json] was not found
  1.1.14 [D:\Program Files (x86)\dotnet\sdk]
  2.1.509 [D:\Program Files (x86)\dotnet\sdk]
  2.2.109 [D:\Program Files (x86)\dotnet\sdk]
Failed exitCode=-2147450735, command=dotnet restore "D:\home\site\repository\Microsoft.Health.Fhir.sln"
An error has occurred during web site deployment.
Install the [3.1.100] .NET Core SDK or update [D:\home\site\repository\global.json] with an installed .NET Core SDK:
A compatible installed .NET Core SDK for global.json version [3.1.100] from [D:\home\site\repository\global.json] was not found\r\nInstall the [3.1.100] .NET Core SDK or update [D:\home\site\repository\global.json] with an installed .NET Core SDK:\r\nD:\Program Files (x86)\SiteExtensions\Kudu\85.11214.4277\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"`

**Comment by hansenms** [comment]
You cannot use the in-web-app (Kudu) build after we upgraded to .NET Core 3.1, since that SDK is not installed in Web Apps (yet). We are having a lot of problems trying to hit the specific versions of .NET Core SDK available in different clouds (Azure commercial, Azure Government, etc) and we have decided to change the template to pull builds from a storage account. If you deploy the template now (from scratch), it will work. But you cannot do the in Kudu build. 

We will likely switch to a container deployment in the future, but we will not go back to Kudu builds.
