### ISSUE TITLE
Description of the purpose of each of the tables in the SQL Database backend

### ISSUE THREAD

**Issue by uxbridgeroad** [microsoft/fhir-server#886]
**User story**
As a DB user, I want to be able to understand the purpose of each of the tables in the SQL Database backend  and understand their relationship to incoming API resources. 

**Acceptance criteria**

1. When I query the the SQL Database containing FHIR resources, I can understand & link the data received for a new / update resource.
2. When I query the the SQL Database containing FHIR resources, I **can decode the contents in RawResource column of Resource table.**

**Comment by hansenms** [comment]
I am reading this user story as "I would like to understand the schema of the SQL data base so that I can read and write FHIR resources directly in the database without going through the FHIR API". 

Am I understanding that correctly?

If that is the case, I would say that it is a pretty standard patterns used to several FHIR servers. We have a table of raw FHIR resources and then extracted search parameters in other tables. The search parameters are grouped by the types of searches that you would typically need to support in FHIR, e.g. token, composite, etc.

The FHIR resources are stored in zipped form in the raw resource table to save space. 

In general, you should not access FHIR resources directly in the database and you certainly should not attempt to write anything directly into the database, since a lot of work is done during writes to extract and index search parameters. It would not be advisable to attempt to do that manually. 

It sounds like you are looking for a schema where you can access the FHIR data (read and write) more directly. This is not how the database schemas was designed. It was designed to serve FHIR queries efficiently.

**Comment by uxbridgeroad** [comment]
>>I am reading this user story as "I would like to understand the schema of the SQL data base so that I can read and write FHIR resources directly in the database without going through the FHIR API".

>>Am I understanding that correctly?

This is not the intention. I do not want to bypass the  FHIR API. 
I just want to understand in as much detail as possible how each of the tables in the DB schema is being used to server the FHIR resources. Is there a design doc for this schema and possible some example to help understand?

When I have looked at the contents of the Cosmos DB implementation, the resource contents seem easy to follow plus the meta dat used for indexing.


I think you have answered one of my queries already  re. the  encoded contents in RawResource column of Resource table. 
>>The FHIR resources are stored in zipped form in the raw resource table to save space.
This is just the zipped content of the original resource. 
Thanks.

**Comment by hansenms** [comment]
The pattern is actually very similar to the Cosmos DB. In the Cosmos DB schema we also store the raw resource in a field (it is not zipped, but maybe it should have been) and then the search parameters are extracted as fields based on the types of search parameters. The SQL model is similar, however, here we store the search parameters in separate tables and link them back to the original resource. So I would say it follows the same pattern.

@johnstairs, is there a design doc we could add to the repo?

**Comment by CaitlinV39** [comment]
@johnstairs bumping for Michael's question on the design doc.

**Comment by EXPEkesheth** [comment]
Closing as old issue. Please reopen if the request holds true still.
