### ISSUE TITLE
Data flow through the FHIR server 

### ISSUE THREAD

**Issue by uxbridgeroad** [microsoft/fhir-server#887]
**User story**
As a developer, I want to be able to understand  the Data flow through the FHIR server so that I can trace the flow when a PUT / GET /  POST of a resource. such as /Patient.

From what I see, there is no "hard coded"  switch for each of the  > 120 FHIR resources (all the resources in the Firely official package of FHIR resources. What (ASP.net) pattern is being used to detect, validate and route the resource and its data to the DB? 

Which classes/modules are implement these flow.?

If I added a temporary class /POCO to the Firely official package of FHIR resources e.g "Dog", would it be transparently accepted as new REST endpoint, stored in the DB and retrieved via a search query?

Thanks

**Comment by hansenms** [comment]
I am not sure this question can be answered generically. There are (of course) quite a fee moving parts in something like a FHIR server. I would recommend starting with @brendankowitz's FHIR Dev Days presentation on how to hack the FHIR server. If you were an attendee you should have access already and otherwise you will have access in a few months when they open it up.

I would start from the data layer (persistence provider) and move upwards using debugger and usual tools. 

The FHIR server uses the mediator pattern and search, upsert, etc. requests ultimately end up with handlers that interact with the data layer, e.g. a search would end up with the SearchResourceHandler: https://github.com/microsoft/fhir-server/blob/master/src/Microsoft.Health.Fhir.Shared.Core/Features/Search/SearchResourceHandler.cs, etc. If you look for the handlers you will find much of the interaction with the data layer. The requests make it from the controllers down to the handlers. 

However, it sounds like your question is really about adding custom resources and whether a custom resource (if added to the firely .NET API) would end up "just working" in the FHIR server. I would say that there would be quite some steps involved in that and it would depend on the nature of the resource, search parameters, etc. 

I am not sure there is anything actionable for us here, but I will see if you have additional questions before closing this issue.

**Comment by uxbridgeroad** [comment]
I have indeed looked at the recording from @brendankowitz's FHIR Dev Days and it sounds like it contains some really useful pointers. ( and much of what I am looking for). Unfortunately, the video was recorded from such a distance (with no zooms) it is impossible to see anything onscreen Brendan is describing nor follow what seems to be very useful instructions.
Furthermore, the links to the sample code demo'd are illegible and there were no slides uploaded with the video.
Is there an equivalent instructional video or blog available or planned?
Is it possible to link to the slides covered or even the demo code repo?

Thanks.

**Comment by hansenms** [comment]
I don't know if @brendankowitz can provide any links here, but there is no other recording of the presentation, so we would have to make a new one. Realistically, that is not likely to happen in the next several weeks, but we will discuss if we should make some more content. Thanks for bringing it up, we have discussed it a few times, but it is the sort of thing that tends to fall off the list with other stuff taking priority.

**Comment by uxbridgeroad** [comment]
>>However, it sounds like your question is really about adding custom resources and whether a custom >>resource (if added to the firely .NET API) would end up "just working" in the FHIR server. I would say >>that there would be quite some steps involved in that and it would depend on the nature of the >>resource, search parameters, etc.

Would it be possible to walk through how this could be achieved?
Maybe  a simple new resource with a few attributes and a search on one of those attributes?
Or renaming an existing resource, added a new attribute to that renamed resource and making that new attribute searchable?

**Comment by hansenms** [comment]
We honestly don't have a cookbook for adding a custom resource and doing a "walk through" of that would not be straightforward. Moreover, I would say that we are very much discouraging people from using custom resources if at all possible. One of the goals of FHIR and our motivation for being involved is interoperability. Custom resources are really a departure from that. There are some use cases, and we may be making some things a bit easier, but I would not expect us to do anything dramatic to make it easier to do custom resources. 

That said, we do want to get better at building a FHIR server that works with a draft version of the FHIR specification so that if you are proposing changes to the spec, you can build a prototype that works with your proposed changes to the spec. We are doing some investigations to figure out how to best do that but we are not quite there yet. 

So if we do some walk-throughs, they will probably be focused on how to support a new data layer (if you have a legacy database) and not on how to depart from the FHIR specification. Hope that makes sense.

**Comment by uxbridgeroad** [comment]
Actually, the scenario I am interested in is that of testing upcoming draft or milestone candidates in the existing FHIR Server release pipeline rather than completely custom resources. Specifically, I want to be able to understand the steps I need to follow to trial the recent R5 alpha released by the firely team. So indeed very close to what you are working on. If at all possible it would be great to have access to or collaborate on a fork where this scenario is being investigated.
Cheers!

**Comment by hansenms** [comment]
You already have an issue open on that: https://github.com/microsoft/fhir-server/issues/862 and we are working on it. We will have aim to merge this in in the next couple of weeks. I’m going to close this issue as it is a duplicate.

**Comment by uxbridgeroad** [comment]
I am not sure if it is a duplicate. #862  is a specific case of using the R5 alpha code where as #887 is requesting more detailed design information on how the FHIR Server handles/ processes resource requests. There were also a number of potential avenues identified in in your comments which could be followed up. If possible, I would prefer to have it remain open.

**Comment by hansenms** [comment]
I can reopen this, however, I am not sure there is anything immediately actionable besides providing an example of how to get an R5 version of the server stood up, which we will do. 

I understand you would like some more documents or/or videos walk-throughs, etc. However, tracking that with an issue will probably not get that done.

I will reopen for now.

**Comment by brendankowitz** [comment]
> I have indeed looked at the recording from @brendankowitz's FHIR Dev Days and it sounds like it contains some really useful pointers. ( and much of what I am looking for). Unfortunately, the video was recorded from such a distance (with no zooms) it is impossible to see anything onscreen Brendan is describing nor follow what seems to be very useful instructions.
> Furthermore, the links to the sample code demo'd are illegible and there were no slides uploaded with the video.
> Is there an equivalent instructional video or blog available or planned?
> Is it possible to link to the slides covered or even the demo code repo?
> 
> Thanks.

Sorry about this, I've put the slides here: https://github.com/brendankowitz/FHIRDevDays/blob/master/2019/Amsterdam/DD19Adam_HackingFHIRServerForAzure.pdf, includes screenshots from the demos.

**Comment by brendankowitz** [comment]
Work on the draft spec is starting in an R5 feature Branch (https://github.com/microsoft/fhir-server/tree/feature/r5). There isn't anything there you can deploy just yet though.

Although we would like to merge more of these layers to be version agnostic, the work right now involves adding in an R5 version at these different layers:
![image](https://user-images.githubusercontent.com/197221/74674833-13916b00-5167-11ea-9b19-c793ebafa8b4.png)

There is also a little more work in getting the new "search-parameter.json" and "compartment.json" (https://github.com/microsoft/fhir-server/tree/master/src/Microsoft.Health.Fhir.R4.Core/Features/Definition) files going (they don't always parse correctly and sometimes require fixes/coding/features).

The answer to the question above is that if there are new resources in the fhir-net-api packages, yes as long as they are reflected in ModelInfo they will be accepted and stored.

**Comment by uxbridgeroad** [comment]
Thanks @brendankowitz for the uploaded docs & code links. The recording is significantly more useful.

**Comment by CaitlinV39** [comment]
@uxbridgeroad I wanted to follow up to see if there are any additional questions you'd like us to track on this issue or if you are okay to close? Thanks!

**Comment by uxbridgeroad** [comment]
@CaitlinV39 this can be closed. Thanks for the support.
